name: release

on: 
  push: 
   branches: 
    - naster
    
jobs: 
  release: 
   runs-on: ubuntu-latest

   steps: 
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Setuo Node.js
      uses: actions/node@v2
      with:
        node-version: 16
  
    - name: Install dependencies
      run: npm install

    - name: Semantic Release
      run: npx semantic-release
      env: 
       GH_TOKEN: ${{ secrets.GH_TOKEN_NEW }}